[solution]
name = "wby-solution-v1"      # Solution name
definition = "moe_fp8_block_scale_ds_routing_topk8_ng8_kg4_e32_h7168_i2048"          # Track: fused_moe | sparse_attention | gated_delta_net
author = "wby"              # Team/author name

[build]
language = "triton"                 # triton | cuda
entry_point = "kernel.py::run"  # Triton export: file::function_name
destination_passing_style = true
